// pages/collection/collection.js
Page({

  /**
   * 页面的初始数据
   */
  data: {
    category:["鱼类","昆虫","艺术品"],
    tabCur : 0,
    notSearch:true,
    searchList:[],
    searchCategory:"",
    fishList:[
      {
        index:1,
        name:"红目鲫",
        price:900,
        }, 
        {
        index:2,
        name:"溪哥",
        price:200,
        }, 
        {
        index:3,
        name:"鲫鱼",
        price:160,
        }, 
        {
        index:4,
        name:"雅罗鱼",
        price:240,
        }, 
        {
        index:5,
        name:"鲤鱼",
        price:300,
        }, 
        {
        index:6,
        name:"锦鲤",
        price:4000,
        }, 
        {
        index:7,
        name:"金鱼",
        price:1300,
        }, 
        {
        index:8,
        name:"龙睛金鱼",
        price:1300,
        }, 
        {
        index:9,
        name:"兰寿金鱼",
        price:4500,
        }, 
        {
        index:10,
        name:"稻田鱼",
        price:300,
        }, 
        {
        index:11,
        name:"淡水龙虾",
        price:200,
        }, 
        {
        index:12,
        name:"鳖",
        price:3750,
        }, 
        {
        index:13,
        name:"拟鳄龟",
        price:5000,
        }, 
        {
        index:14,
        name:"蝌蚪",
        price:100,
        }, 
        {
        index:15,
        name:"青蛙",
        price:120,
        }, 
        {
        index:16,
        name:"塘鳢鱼",
        price:400,
        }, 
        {
        index:17,
        name:"泥鳅",
        price:400,
        }, 
        {
        index:18,
        name:"鲶鱼",
        price:800,
        }, 
        {
        index:19,
        name:"黑鱼",
        price:5500,
        }, 
        {
        index:20,
        name:"蓝鳃太阳鱼",
        price:180,
        }, 
        {
        index:21,
        name:"黄鲈鱼",
        price:300,
        }, 
        {
        index:22,
        name:"黑鲈鱼",
        price:320,
        }, 
        {
        index:23,
        name:"吴郭鱼",
        price:800,
        }, 
        {
        index:24,
        name:"白斑狗鱼",
        price:1800,
        }, 
        {
        index:25,
        name:"西太公鱼",
        price:400,
        }, 
        {
        index:26,
        name:"香鱼",
        price:900,
        }, 
        {
        index:27,
        name:"樱花钩吻鲑",
        price:1000,
        }, 
        {
        index:28,
        name:"花羔红点鲑",
        price:3800,
        }, 
        {
        index:29,
        name:"金鳟",
        price:15000,
        }, 
        {
        index:30,
        name:"远东哲罗鱼",
        price:15000,
        }, 
        {
        index:31,
        name:"鲑鱼",
        price:700,
        }, 
        {
        index:32,
        name:"帝王鲑",
        price:1800,
        }, 
        {
        index:33,
        name:"中华绒螯蟹",
        price:2000,
        }, 
        {
        index:34,
        name:"孔雀鱼",
        price:1300,
        }, 
        {
        index:35,
        name:"温泉医生鱼",
        price:1500,
        }, 
        {
        index:36,
        name:"神仙鱼",
        price:3000,
        }, 
        {
        index:37,
        name:"斗鱼",
        price:2500,
        }, 
        {
        index:38,
        name:"霓虹灯鱼",
        price:500,
        }, 
        {
        index:39,
        name:"彩虹鱼",
        price:800,
        }, 
        {
        index:40,
        name:"食人鱼",
        price:2500,
        }, 
        {
        index:41,
        name:"骨舌鱼",
        price:1000,
        }, 
        {
        index:42,
        name:"黄金河虎",
        price:15000,
        }, 
        {
        index:43,
        name:"雀鳝",
        price:6000,
        }, 
        {
        index:44,
        name:"巨骨舌鱼",
        price:10000,
        }, 
        {
        index:45,
        name:"恩氏多鳍鱼",
        price:15000,
        }, 
        {
        index:46,
        name:"鲟鱼",
        price:10000,
        }, 
        {
        index:47,
        name:"海蝴蝶",
        price:1000,
        }, 
        {
        index:48,
        name:"海马",
        price:1100,
        }, 
        {
        index:49,
        name:"小丑鱼",
        price:650,
        }, 
        {
        index:50,
        name:"拟刺尾鲷",
        price:1000,
        }, 
        {
        index:51,
        name:"耳带蝴蝶鱼",
        price:1000,
        }, 
        {
        index:52,
        name:"苏眉鱼",
        price:10000,
        }, 
        {
        index:53,
        name:"狮子鱼",
        price:500,
        }, 
        {
        index:54,
        name:"河豚",
        price:5000,
        }, 
        {
        index:55,
        name:"刺豚",
        price:250,
        }, 
        {
        index:56,
        name:"凤尾鱼",
        price:200,
        }, 
        {
        index:57,
        name:"竹荚鱼",
        price:150,
        }, 
        {
        index:58,
        name:"条石鲷",
        price:5000,
        }, 
        {
        index:59,
        name:"鲈鱼",
        price:400,
        }, 
        {
        index:60,
        name:"鲷鱼",
        price:3000,
        }, 
        {
        index:61,
        name:"鲽鱼",
        price:300,
        }, 
        {
        index:62,
        name:"比目鱼",
        price:800,
        }, 
        {
        index:63,
        name:"鱿鱼",
        price:500,
        }, 
        {
        index:64,
        name:"裸胸鳝",
        price:2000,
        }, 
        {
        index:65,
        name:"五彩鳗",
        price:600,
        }, 
        {
        index:66,
        name:"鲔鱼",
        price:7000,
        }, 
        {
        index:67,
        name:"旗鱼",
        price:10000,
        }, 
        {
        index:68,
        name:"白面弄鱼",
        price:4500,
        }, 
        {
        index:69,
        name:"鬼头刀",
        price:6000,
        }, 
        {
        index:70,
        name:"翻车鱼",
        price:4000,
        }, 
        {
        index:71,
        name:"鳐鱼",
        price:3000,
        }, 
        {
        index:72,
        name:"锯鲨",
        price:12000,
        }, 
        {
        index:73,
        name:"双髻鲨",
        price:8000,
        }, 
        {
        index:74,
        name:"鲨鱼",
        price:15000,
        }, 
        {
        index:75,
        name:"鲸鲨",
        price:13000,
        }, 
        {
        index:76,
        name:"吸盘鱼",
        price:1500,
        }, 
        {
        index:77,
        name:"灯笼鱼",
        price:2500,
        }, 
        {
        index:78,
        name:"皇带鱼",
        price:9000,
        }, 
        {
        index:79,
        name:"太平洋桶眼鱼",
        price:15000,
        }, 
        {
        index:80,
        name:"矛尾鱼",
        price:15000,
        }, 
        
    ],
    insectList:[
      {
        index:1,
        name:"白粉蝶",
        price:160,
        }, 
        {
        index:2,
        name:"斑缘点粉蝶",
        price:160,
        }, 
        {
        index:3,
        name:"凤蝶",
        price:240,
        }, 
        {
        index:4,
        name:"乌鸦凤蝶",
        price:2500,
        }, 
        {
        index:5,
        name:"青带凤蝶",
        price:300,
        }, 
        {
        index:6,
        name:"大白斑蝶",
        price:1000,
        }, 
        {
        index:7,
        name:"大紫蛱蝶",
        price:300,
        }, 
        {
        index:8,
        name:"大桦斑蝶",
        price:140,
        }, 
        {
        index:9,
        name:"大蓝闪蝶",
        price:4000,
        }, 
        {
        index:10,
        name:"彩袄蛱蝶",
        price:3000,
        }, 
        {
        index:11,
        name:"红颈凤蝶",
        price:2500,
        }, 
        {
        index:12,
        name:"亚历山大凤蝶",
        price:4000,
        }, 
        {
        index:13,
        name:"飞蛾",
        price:130,
        }, 
        {
        index:14,
        name:"皇蛾",
        price:3000,
        }, 
        {
        index:15,
        name:"日落蛾",
        price:2500,
        }, 
        {
        index:16,
        name:"中华剑角蝗",
        price:200,
        }, 
        {
        index:17,
        name:"飞蝗",
        price:600,
        }, 
        {
        index:18,
        name:"稻蝗",
        price:400,
        }, 
        {
        index:19,
        name:"蚱蜢",
        price:160,
        }, 
        {
        index:20,
        name:"蟋蟀",
        price:130,
        }, 
        {
        index:21,
        name:"铃虫",
        price:430,
        }, 
        {
        index:22,
        name:"螳螂",
        price:430,
        }, 
        {
        index:23,
        name:"兰花螳螂",
        price:2400,
        }, 
        {
        index:24,
        name:"蜜蜂",
        price:200,
        }, 
        {
        index:25,
        name:"黄蜂",
        price:2500,
        }, 
        {
        index:26,
        name:"油蝉",
        price:250,
        }, 
        {
        index:27,
        name:"斑透翅蝉",
        price:300,
        }, 
        {
        index:28,
        name:"熊蝉",
        price:500,
        }, 
        {
        index:29,
        name:"寒蝉",
        price:400,
        }, 
        {
        index:30,
        name:"暮蝉",
        price:550,
        }, 
        {
        index:31,
        name:"蝉蜕",
        price:10,
        }, 
        {
        index:32,
        name:"红蜻蜓",
        price:180,
        }, 
        {
        index:33,
        name:"绿胸晏蜓",
        price:230,
        }, 
        {
        index:34,
        name:"无霸勾蜓",
        price:4500,
        }, 
        {
        index:35,
        name:"豆娘",
        price:500,
        }, 
        {
        index:36,
        name:"萤火虫",
        price:300,
        }, 
        {
        index:37,
        name:"蝼蛄",
        price:500,
        }, 
        {
        index:38,
        name:"水黾",
        price:130,
        }, 
        {
        index:39,
        name:"龙虱",
        price:800,
        }, 
        {
        index:40,
        name:"田鳖",
        price:2000,
        }, 
        {
        index:41,
        name:"椿象",
        price:120,
        }, 
        {
        index:42,
        name:"人面蝽象",
        price:1000,
        }, 
        {
        index:43,
        name:"瓢虫",
        price:200,
        }, 
        {
        index:44,
        name:"虎甲虫",
        price:1500,
        }, 
        {
        index:45,
        name:"吉丁虫",
        price:2400,
        }, 
        {
        index:46,
        name:"提琴虫",
        price:450,
        }, 
        {
        index:47,
        name:"星天牛",
        price:350,
        }, 
        {
        index:48,
        name:"琉璃星天牛",
        price:3000,
        }, 
        {
        index:49,
        name:"宝石象鼻虫",
        price:800,
        }, 
        {
        index:50,
        name:"蜣螂",
        price:3000,
        }, 
        {
        index:51,
        name:"雪隐金龟",
        price:300,
        }, 
        {
        index:52,
        name:"宝石金龟",
        price:10000,
        }, 
        {
        index:53,
        name:"白铜锣花金龟",
        price:200,
        }, 
        {
        index:54,
        name:"歌利亚大角花金龟",
        price:8000,
        }, 
        {
        index:55,
        name:"锯锹形虫",
        price:2000,
        }, 
        {
        index:56,
        name:"深山锹形虫",
        price:1000,
        }, 
        {
        index:57,
        name:"大锹形虫",
        price:10000,
        }, 
        {
        index:58,
        name:"彩虹锹形虫",
        price:6000,
        }, 
        {
        index:59,
        name:"细身赤锹形虫",
        price:8000,
        }, 
        {
        index:60,
        name:"黄金鬼锹形虫",
        price:12000,
        }, 
        {
        index:61,
        name:"长颈鹿锹形虫",
        price:12000,
        }, 
        {
        index:62,
        name:"独角仙",
        price:1350,
        }, 
        {
        index:63,
        name:"高卡萨斯南洋大兜虫",
        price:8000,
        }, 
        {
        index:64,
        name:"象兜虫",
        price:8000,
        }, 
        {
        index:65,
        name:"长戟大兜虫",
        price:12000,
        }, 
        {
        index:66,
        name:"竹节虫",
        price:600,
        }, 
        {
        index:67,
        name:"叶竹节虫",
        price:600,
        }, 
        {
        index:68,
        name:"蓑衣虫",
        price:600,
        }, 
        {
        index:69,
        name:"蚂蚁",
        price:80,
        }, 
        {
        index:70,
        name:"寄居蟹",
        price:1000,
        }, 
        {
        index:71,
        name:"海蟑螂",
        price:200,
        }, 
        {
        index:72,
        name:"苍蝇",
        price:60,
        }, 
        {
        index:73,
        name:"蚊子",
        price:130,
        }, 
        {
        index:74,
        name:"跳蚤",
        price:70,
        }, 
        {
        index:75,
        name:"蜗牛",
        price:250,
        }, 
        {
        index:76,
        name:"鼠妇",
        price:250,
        }, 
        {
        index:77,
        name:"蜈蚣",
        price:300,
        }, 
        {
        index:78,
        name:"蜘蛛",
        price:600,
        }, 
        {
        index:79,
        name:"狼蛛",
        price:8000,
        }, 
        {
        index:80,
        name:"蝎子",
        price:8000,
        }, 
    ],
  
    artList:[
      {
        name:"磅礴的名画",
        type:"画",
        index:1,
        },
        {
        name:"常见的名画",
        type:"画",
        index:2,
        },
        {
        name:"沉默的名画",
        type:"画",
        index:3,
        },
        {
        name:"充满母爱的雕塑",
        type:"雕塑",
        index:4,
        },
        {
        name:"出乎意料的雕塑",
        type:"雕塑",
        index:5,
        },
        {
        name:"粗野的名画右半边",
        type:"画",
        index:6,
        },
        {
        name:"粗野的名画左半边",
        type:"画",
        index:7,
        },
        {
        name:"动人的名画",
        type:"画",
        index:8,
        },
        {
        name:"端庄的名画",
        type:"画",
        index:9,
        },
        {
        name:"婀娜的名画",
        type:"画",
        index:10,
        },
        {
        name:"光线的名画",
        type:"画",
        index:11,
        },
        {
        name:"惊人的名画",
        type:"画",
        index:12,
        },
        {
        name:"俊俏的名画",
        type:"画",
        index:13,
        },
        {
        name:"美丽的雕塑",
        type:"雕塑",
        index:15,
        },
        {
        name:"名贵的名画",
        type:"画",
        index:16,
        },
        {
        name:"漂亮的名画",
        type:"画",
        index:17,
        },
        {
        name:"平静的名画",
        type:"画",
        index:18,
        },
        {
        name:"强健的名画",
        type:"画",
        index:19,
        },
        {
        name:"强壮的雕塑",
        type:"雕塑",
        index:20,
        },
        {
        name:"热闹的名画",
        type:"画",
        index:21,
        },
        {
        name:"闪烁的名画",
        type:"画",
        index:22,
        },
        {
        name:"神秘的雕塑",
        type:"雕塑",
        index:23,
        },
        {
        name:"神秘的名画",
        type:"画",
        index:24,
        },
        {
        name:"神圣的雕塑",
        type:"雕塑",
        index:25,
        },
        {
        name:"石头颅雕塑",
        type:"雕塑",
        index:26,
        },
        {
        name:"似曾相识的雕塑",
        type:"雕塑",
        index:27,
        },
        {
        name:"舒适的名画",
        type:"画",
        index:28,
        },
        {
        name:"肃穆的名画",
        type:"画",
        index:29,
        },
        {
        name:"伟大的雕塑",
        type:"雕塑",
        index:30,
        },
        {
        name:"武士的雕刻",
        type:"雕塑",
        index:31,
        },
        {
        name:"细致的名画",
        type:"画",
        index:32,
        },
        {
        name:"线索的雕塑",
        type:"雕塑",
        index:33,
        },
        {
        name:"学术性的名画",
        type:"画",
        index:34,
        },
        {
        name:"英挺的雕塑",
        type:"雕塑",
        index:35,
        },
        {
        name:"勇敢的名画",
        type:"画",
        index:36,
        },
        {
        name:"优美的名画",
        type:"画",
        index:37,
        },
        {
        name:"有名的名画",
        type:"画",
        index:38,
        },
        {
        name:"有趣的名画",
        type:"画",
        index:39,
        },
        {
        name:"远古的雕塑",
        type:"雕塑",
        index:40,
        },
        {
        name:"珍贵的名画",
        type:"画",
        index:41,
        },
        
    ]

  },

  tabSelect(e){
    this.setData({
      tabCur:e.currentTarget.dataset.id ,
    })
  },  
  toDetail(e){
    var app=getApp()
    var c = e.currentTarget.dataset.category
    var index = e.currentTarget.dataset.id
    app.globalData.detailIndex= index
    switch(c){
      case "insect":
        app.globalData.category = "insect"
        break
      case "fish":
        app.globalData.category = "fish"
        break
      case "art":
        app.globalData.category = "art"
        break
    }
    wx.navigateTo({
      url: '/pages/colletionDetail/colletionDetail',
    })
  },
  bindSearch(e){
     var str = e.detail.value
     var tempList =[]
     var result = []
    
     if(str.length!=0){
      this.setData({
        searchList:[],
        notSearch:false,
      })
     switch(this.data.tabCur){
      case 0:
        tempList = this.data.fishList
        this.setData({
          searchCategory:"fish"
        })
        break
      case 1:
        tempList = this.data.insectList
        this.setData({
          searchCategory:"insect"
        })
        break
      case 2:
        tempList=this.data.artList
        this.setData({
          searchCategory:"art"
        })
        break
     }
     
     for(let i=0;i<tempList.length;i++){
       if(tempList[i].name.indexOf(str)!=-1){
         result.push(tempList[i])
       }
     }
     this.setData({
       searchList:result
     })
     console.log(this.data.searchList)
    }else{
      this.setData({
        notSearch:true
      })
    }
    
  },

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function (options) {

  },

  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady: function () {

  },

  /**
   * 生命周期函数--监听页面显示
   */
  onShow: function () {

  },

  /**
   * 生命周期函数--监听页面隐藏
   */
  onHide: function () {

  },

  /**
   * 生命周期函数--监听页面卸载
   */
  onUnload: function () {

  },

  /**
   * 页面相关事件处理函数--监听用户下拉动作
   */
  onPullDownRefresh: function () {

  },

  /**
   * 页面上拉触底事件的处理函数
   */
  onReachBottom: function () {

  },

  /**
   * 用户点击右上角分享
   */
  onShareAppMessage: function () {

  }
})